- src/main/java/com/example/dp/domain/model/TimeEntity.java
생성일자, 수정일자와 같은 날짜 데이터를 쓰는 공용Entity 추가 
- domain 밑 model 디렉토리에 TimeEntity추가
> Feat : 공용 TimeEntity 추가

- src/main/java/com/example/dp/domain/cart/Cart.java
- src/main/java/com/example/dp/domain/cart/entity/Cart.java
장바구니 엔티티 추가 
- 장바구니 엔티티 추가 
- User객체 미구현 상태로 오류 발생
> [#2] feat: add Cart Entity

- src/main/java/com/example/dp/global/config/JpaAuditing.java
Jpa Auditing Cofigration 추가
config 파일 추가 
- 없음
-
> feat: jpa auditing config 추가

- src/main/java/com/example/dp/domain/menu/entity/Category.java
- src/main/java/com/example/dp/domain/menu/entity/Menu.java
- src/main/java/com/example/dp/domain/menu/entity/MenuCategory.java
Menu domain entity추가
- Menu Entity 추가
- Category Entity 추가
- MenuCategory Entity 추가
- close #7
> [#7] feat: add Menu Entity

- src/main/java/com/example/dp/DpApplication.java
- src/main/java/com/example/dp/domain/Test.java
- src/main/java/com/example/dp/domain/category/entity/Category.java
- src/main/java/com/example/dp/domain/like/entity/Like.java
- src/main/java/com/example/dp/domain/menu/entity/Menu.java
- src/main/java/com/example/dp/domain/menucategory/entity/MenuCategory.java
- src/main/java/com/example/dp/domain/model/TimeEntity.java
- src/main/java/com/example/dp/domain/order/entity/Order.java
- src/main/java/com/example/dp/domain/order/entity/OrderStatus.java
- src/main/java/com/example/dp/domain/ordermenu/entity/OrderMenu.java
- src/main/java/com/example/dp/domain/user/UserRole.java
- src/main/java/com/example/dp/domain/user/controller/UserController.java
- src/main/java/com/example/dp/domain/user/dto/request/UserSignupRequestDto.java
- src/main/java/com/example/dp/domain/user/repository/UserRepository.java
- src/main/java/com/example/dp/domain/user/service/UserService.java
- src/main/java/com/example/dp/global/Test1.java
모든 도메인의 엔티티 생성 작업과 코드 정렬 작업
- 모든 도메인의 엔티티 클래스 생성
- 코드 포멧팅
- close #12
> [#12] Feature/add all entity

- build.gradle
- src/main/java/com/example/dp/global/config/JasyptConfig.java
- src/test/java/com/example/dp/global/config/JasyptConfigTest.java
Jasypt 적용
- JasyptConfig 파일 적용 및 의존성 추가, 테스트 코드 작성
- close #18
> [#18] Feature/jasypt

- src/main/java/com/example/dp/domain/cart/controller/CartController.java
- src/main/java/com/example/dp/domain/cart/dto/CartResponseDto.java
- src/main/java/com/example/dp/domain/cart/entity/Cart.java
- src/main/java/com/example/dp/domain/cart/repository/CartRepository.java
- src/main/java/com/example/dp/domain/cart/service/CartService.java
- src/main/java/com/example/dp/domain/cart/service/impl/CartServiceImpl.java
- src/main/java/com/example/dp/domain/order/entity/Order.java
- src/main/java/com/example/dp/domain/order/entity/OrderMenu.java
장바구니 조회 메서드 추가
-  사용자의 장바구니 리스트 조회
> Feat/ 장바구니 조회 메서드 추가

- build.gradle
- src/main/java/com/example/dp/domain/order/repository/OrderRepository.java
- src/main/java/com/example/dp/domain/review/controller/ReviewController.java
- src/main/java/com/example/dp/domain/review/dto/request/ReviewRequestDto.java
- src/main/java/com/example/dp/domain/review/dto/response/ReviewResponseDto.java
- src/main/java/com/example/dp/domain/review/repository/ReviewRepository.java
- src/main/java/com/example/dp/domain/review/service/ReviewService.java
- src/main/java/com/example/dp/domain/review/service/impl/ReviewServiceImpl.java
- src/main/java/com/example/dp/domain/review/validator/ReviewValidator.java
- src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
- src/test/resources/application.yml
Review 생성 기능 구현
- Review 생성 기능 구현
- Review 생성 기능 테스트코드 추가
- 테스트 관련 라이브러리 추가
- AssertJ, FixtureMonkey, H2
- 테스트 application.yml 추가
- close #24
> [#24] Feature/review create

- src/main/java/com/example/dp/domain/cart/controller/CartController.java
Controller단 CartResponseDto 문제 수정 
- import com.example.dp.domain.cart.dto.response.CartResponseDto로 변경 
-
> Refactor : import url 주소 변경

- src/main/java/com/example/dp/domain/review/controller/ReviewController.java
UserDetailsImpl import 코드 추가
- UserDetailsImpl import 코드 추가
> [Feature/review create] UserDetailsImpl 추가

- src/main/java/com/example/dp/domain/review/controller/ReviewController.java
- src/main/java/com/example/dp/domain/review/entity/Review.java
- src/main/java/com/example/dp/domain/review/service/ReviewService.java
- src/main/java/com/example/dp/domain/review/service/impl/ReviewServiceImpl.java
- src/main/java/com/example/dp/domain/review/validator/ReviewValidator.java
- src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
리뷰 수정 기능 추가
- 리뷰 수정 기능 추가
- 테스트 코드 추가
- `ReviewValidator.validExistReview(ReviewRepository, order)` -> `ReviewValidator.validExistReview(boolean)`
- close #35
> [#35]Feature/review update - 리뷰 수정

- src/main/java/com/example/dp/domain/order/entity/Order.java
- src/main/java/com/example/dp/domain/review/controller/ReviewController.java
- src/main/java/com/example/dp/domain/review/service/ReviewService.java
- src/main/java/com/example/dp/domain/review/service/impl/ReviewServiceImpl.java
- src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
리뷰 삭제 기능 구현
- 리뷰 삭제 기능 구현
- 테스트 코드 작성
- close #40
> [#40] Feature/review delete

- src/main/java/com/example/dp/domain/cart/controller/CartController.java
CartController 추가
- CartController 추가
> Feat : CartController 추가

- build.gradle
- src/main/java/com/example/dp/global/config/WebSecurityConfig.java
Swagger 추가
- Swagger 추가
- 
- close #52
> [#52]Chore: Swagger 추가

- src/main/java/com/example/dp/domain/admin/controller/AdminMenuController.java
- src/main/java/com/example/dp/domain/admin/service/impl/AdminMenuServiceImpl.java
- src/main/java/com/example/dp/domain/category/controller/CategoryController.java
- src/main/java/com/example/dp/domain/category/dto/request/CategoryRequestDto.java
- src/main/java/com/example/dp/domain/category/dto/response/CategoryResponseDto.java
- src/main/java/com/example/dp/domain/category/entity/Category.java
- src/main/java/com/example/dp/domain/category/exception/CategoryErrorCode.java
- src/main/java/com/example/dp/domain/category/exception/ExistsCategoryTypeException.java
- src/main/java/com/example/dp/domain/category/exception/NotFoundCategoryException.java
- src/main/java/com/example/dp/domain/category/repository/CategoryRepository.java
- src/main/java/com/example/dp/domain/category/service/CategoryService.java
- src/main/java/com/example/dp/domain/category/service/impl/CategoryServiceImpl.java
- src/main/java/com/example/dp/domain/menu/dto/request/MenuRequestDto.java
- src/main/java/com/example/dp/domain/menu/dto/response/MenuDetailResponseDto.java
- src/main/java/com/example/dp/domain/menu/dto/response/MenuSimpleResponseDto.java
- src/main/java/com/example/dp/domain/menu/entity/Menu.java
- src/main/java/com/example/dp/domain/menu/exception/ExistsMenuNameException.java
- src/main/java/com/example/dp/domain/menu/exception/MenuErrorCode.java
- src/main/java/com/example/dp/domain/menu/repository/MenuRepository.java
- src/main/java/com/example/dp/domain/menucategory/entity/MenuCategory.java
- src/main/java/com/example/dp/domain/menucategory/repository/MenuCategoryRepository.java
- src/main/java/com/example/dp/domain/menulike/entity/MenuLike.java
- src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
- src/test/java/com/example/dp/domain/category/service/impl/CategoryServiceImplTest.java
Menu 수정 기능  Patch > Put으로 변경
카테고리 CUD 구현
- Like MenuLike로 이름 변경
- Menu 수정 Put으로 변경
- Menu 삭제시 HttpStatus 코드 수정
- Category CUD 구현
- Category 테스트 코드 구현
- Menu 생성시 카테고리 연결되도록 구현 ( 테스트 못함 )
- 예외처리 정리 예정
- close #34
> Feature/refactor menu crud, Featrue/category cud

- src/main/java/com/example/dp/domain/cart/dto/response/CartResponseDto.java
- src/main/java/com/example/dp/domain/order/dto/response/OrderResponseDto.java
- src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
- src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
CartResponseDto , OrderResponseDto 수정
- Dto에 엔티티 객체 포함되지않게 변경
> Refactor : ResponseDto 수정

- src/main/java/com/example/dp/domain/admin/controller/AdminMenuController.java
- src/main/java/com/example/dp/domain/admin/service/impl/AdminMenuServiceImpl.java
- src/main/java/com/example/dp/domain/category/controller/CategoryController.java
- src/main/java/com/example/dp/domain/category/dto/request/CategoryRequestDto.java
- src/main/java/com/example/dp/domain/category/entity/Category.java
- src/main/java/com/example/dp/domain/category/service/impl/CategoryServiceImpl.java
- src/main/java/com/example/dp/domain/menu/dto/request/MenuRequestDto.java
- src/main/java/com/example/dp/domain/menu/entity/Menu.java
- src/test/java/com/example/dp/domain/category/service/impl/CategoryServiceImplTest.java
Category, Menu 수정
- RequestDto 기본생성자 추가
- Menu, Category Entity 내 update 매개변수 수정
- 삭제 ResponseEntity <Void>로변경
> Refactor : Category, Menu 수정

- src/main/java/com/example/dp/domain/menu/dto/response/MenuDetailResponseDto.java
> Fix : MenuDetailResponseDto 수정

- src/main/java/com/example/dp/domain/review/exception/ReviewErrorCode.java
ReviewErrorCode 메세지 수정
- FORBIDDEN_CREATE 메세지 수정
> Feat: ReviewErrorCode 메세지 수정

- src/main/java/com/example/dp/domain/admin/controller/AdminReviewController.java
- src/main/java/com/example/dp/domain/admin/service/AdminReviewService.java
- src/main/java/com/example/dp/domain/admin/service/impl/AdminReviewServiceImpl.java
- src/test/java/com/example/dp/domain/admin/service/impl/AdminReviewServiceImplTest.java
어드민 리뷰 삭제 기능
- 어드민 리뷰 삭제 기능
- 테스트 코드 추가
- close #72
> Feature/admin review - 어드민 리뷰 삭제 기능

- src/main/java/com/example/dp/domain/menu/controller/MenuController.java
- src/main/java/com/example/dp/domain/menu/service/MenuService.java
- src/main/java/com/example/dp/domain/menu/service/impl/MenuServiceImpl.java
- src/main/java/com/example/dp/domain/menulike/entity/MenuLike.java
- src/main/java/com/example/dp/domain/menulike/repository/MenuLikeRepository.java
- src/test/java/com/example/dp/domain/menu/service/impl/MenuServiceImplTest.java
좋아요 기준으로 메뉴 조회 기능 구현
- 좋아요 기준으로 메뉴 조회 기능 구현
- `MenuLike` 테이블명 수정
- `TB_LIKE` -> `TB_MENULIKE`
- close #67
> Feature/menu read like - 좋아요 기준으로 메뉴 조회 기능 구현

- src/main/java/com/example/dp/domain/admin/controller/AdminUserController.java
- src/main/java/com/example/dp/domain/admin/service/AdminUserService.java
- src/main/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImpl.java
- src/main/java/com/example/dp/domain/user/dto/response/UserResponseDto.java
- src/main/java/com/example/dp/domain/user/exception/NotFoundUserException.java
- src/main/java/com/example/dp/domain/user/exception/UserErrorCode.java
- src/main/java/com/example/dp/domain/user/repository/UserRepository.java
- src/test/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImplTest.java
- src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
- src/test/java/com/example/dp/domain/menu/service/impl/MenuServiceImplTest.java
- src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
- src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
관리자 사용자 조회 구현
- 사용자 단건 조회
- 전체 사용자 조회 (최근가입순)
- 사용자 조회 테스트
- close #76
> Feature/admin user read 관리자 사용자 조회 구현

- src/main/java/com/example/dp/global/config/WebSecurityConfig.java
- src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
- src/test/java/com/example/dp/domain/menu/service/impl/MenuServiceImplTest.java
- src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
> 테스트코드 @Disabled
